<a href="https://colab.research.google.com/github/topchaebol/2/blob/main/0512_pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x=torch.Tensor(3)

In [ ]:
print(x)

tensor([7.9496e-36, 0.0000e+00, 3.7835e-44])


In [ ]:
x2 = torch.Tensor(3,3)

In [ ]:
x2

tensor([[7.9515e-36, 0.0000e+00, 4.4842e-44],
        [8.5479e-44, 4.4842e-44, 1.6255e-43],
        [1.5554e-43, 1.5975e-43, 1.3873e-43]])

In [ ]:
x3 = torch.Tensor(3,3,3,3,3,3,3)

In [ ]:
x3

tensor([[[[[[[ 8.2189e-36,  0.0000e+00,  8.7441e-43],
             [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
             [ 7.7481e-38,  0.0000e+00,  1.4013e-45]],

            [[ 0.0000e+00,  7.7484e-38,  0.0000e+00],
             [ 1.4013e-45,  0.0000e+00,  7.7481e-38],
             [ 0.0000e+00,  3.9236e-44,  4.5876e-41]],

            [[-6.3165e-28,  4.5876e-41,  2.8026e-45],
             [ 1.1210e-44, -4.7698e-17,  4.5876e-41],
             [ 1.4013e-45,  0.0000e+00,  3.9236e-44]]],


           [[[ 2.1019e-44, -5.9028e-29,  4.5876e-41],
             [ 1.4013e-45,  0.0000e+00,  1.4013e-45],
             [ 3.2230e-44,  1.4013e-45,  7.0065e-45]],

            [[ 3.5032e-44,  0.0000e+00,  7.7481e-38],
             [ 0.0000e+00, -4.2677e-30,  4.5876e-41],
             [ 1.4013e-45,  0.0000e+00,  1.4013e-45]],

            [[ 7.0065e-45,  9.8091e-45,  0.0000e+00],
             [ 7.7482e-38,  0.0000e+00,  7.7482e-38],
             [ 0.0000e+00,  7.7482e-38,  0.0000e+00]]],


           [

In [ ]:
a = torch.rand(3,3)

In [ ]:
a

tensor([[0.5808, 0.6890, 0.5676],
        [0.5445, 0.9047, 0.5948],
        [0.8745, 0.4537, 0.2602]])

In [ ]:
b = torch.randn(4,4)

In [ ]:
b

tensor([[-0.0945,  0.2472, -0.4613, -0.3360],
        [-0.1760,  0.4672, -0.1306,  1.3409],
        [-0.4328, -1.1433, -1.6244, -0.6349],
        [ 3.1001, -1.1394,  0.9918, -0.9464]])

넘파이에서 텐서로 변환

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = torch.Tensor(a)
b

tensor([1., 2., 3., 4.])

텐서에서 넘파이로 변환

In [ ]:
a = torch.rand(3,3)
b = a.numpy()
b

array([[5.7309693e-01, 5.5666375e-01, 7.7090394e-01],
       [6.2736887e-01, 6.1719602e-01, 2.7366525e-01],
       [5.8726645e-01, 4.0514022e-01, 1.4007092e-04]], dtype=float32)

array([[0.62319124, 0.32242668, 0.0088945 ],
       [0.63613456, 0.80571336, 0.32609677],
       [0.10890549, 0.05570662, 0.7511179 ]], dtype=float32)

텐서의 형태 변환

In [ ]:
a = torch.rand(3,3)

In [ ]:
a= a.view(1,1,3,3)
a

tensor([[[[0.7450, 0.2540, 0.6398],
          [0.9472, 0.5939, 0.1744],
          [0.9668, 0.3263, 0.2954]]]])

Tensor 합치기

In [ ]:
a = torch.randn(1,1,3,3)
b = torch.randn(1,1,3,3)
c = torch.cat((a,b),0)
c

tensor([[[[-1.3657,  1.1941, -0.0884],
          [-0.3938, -0.0513,  0.5482],
          [ 1.4133,  1.2706,  1.2170]]],


        [[[ 0.0734,  0.9989, -0.5032],
          [-1.0848, -1.1077,  0.3029],
          [ 0.4648, -0.6328, -1.5903]]]])

In [ ]:
x = torch.rand(3,3)
y = torch.rand(3,3)
if torch.cuda.is_available():
  x = x.cuda()
  y = y.cuda()
  sum = x + y 

x.mean()
x.sum()